name: Create Release on Main Push

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "latest"

      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

      - name: Update manifest version
        env:
          NEW_VERSION: ${{ steps.bump.outputs.new_tag }}
        run: sed -i "s/\"version\": \".*\"/\"version\": \"$NEW_VERSION\"/" public/manifest.json

      - name: Build
        run: npm i && npm run build

      - name: Create ZIP file
        run: |
          cd dist && zip -r ../liqui2cal.zip *

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: liqui2cal.zip
          tag_name: ${{ steps.bump.outputs.new_tag }}
